using System;
using System.Collections.Generic;
using System.Linq;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:

 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */

namespace Euler
{
  public class Problem
  {
    static private IEnumerable<long> fibonacci(long n)
    {
      long prev = 0;
      long curr = 1;

      while (curr < n)
      {
        yield return curr;
        long tmp = curr;
        curr += prev;
        prev = tmp;
      }
    }

    static public void Solution()
    {
      Console.WriteLine(fibonacci(4000000)
        .Where(n => n % 2 == 0)
        .Sum());
    }

    static public void Main()
    {
      Euler.TimeWrapper(Solution);
    }
  }
}
