#include "euler.h"
#include <stdio.h>
#include <stdlib.h>

/*
 * Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms
 * will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do
 * not exceed four million, find the sum of the even-valued terms.
 */

static int run(void) {
  NUM_TYPE sum = 0;
  NUM_TYPE curr = 2;
  NUM_TYPE prev = 1;

  while (curr < 4000000) {
    if (curr % 2 == 0) sum += curr;
    NUM_TYPE tmp = curr;
    curr = curr + prev;
    prev = tmp;
  }
  
  printf("%"NUM_TYPE_PRINTF"\n", sum);
  return 0;
}

int main(void) {
  int exit_code = time_wrapper(run);
  if (exit_code != 0) {
    perror("error");
  }

  return EXIT_SUCCESS;
}
