#include "euler.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

/*
 * Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulae:
 *
 * Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
 * Pentagonal  Pn=n(3n-1)/2  1, 5, 12, 22, 35, ...
 * Hexagonal   Hn=n(2n-1)    1, 6, 15, 28, 45, ...
 * It can be verified that T_{285} = P_{165} = H_{143} = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 */

NUM_TYPE triangular(NUM_TYPE n) {
  return n*(n+1)/2;
}

bool is_pentagonal(NUM_TYPE n) {
  double dn = n;
  dn = (1+sqrt(24*n+1))/6;
  return dn == (NUM_TYPE)dn;
}

bool is_hexagonal(NUM_TYPE n) {
  double dn = n;
  dn = (1+sqrt(8*n+1))/4;
  return dn == (NUM_TYPE)dn;
}

static int run(void) {
  for (NUM_TYPE n = 286;; n++) {
    NUM_TYPE t = triangular(n);
    if (is_pentagonal(t) && is_hexagonal(t)) {
      printf("%"NUM_TYPE_PRINTF"\n", t);
      return 0;
    }
  }
}

int main(void) {
  int exit_code = time_wrapper(run);
  if (exit_code != 0) {
    perror("error");
  }

  return EXIT_SUCCESS;
}
