#!/usr/bin/python2
#-*- encoding:utf-8 -*-

"""
Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will
be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""

import euler

def fibonacci(n):
    prev_prev = 0
    prev = 1
    current = 1

    while current < n:
        yield current
        prev_prev = prev
        prev = current
        current = prev_prev + prev

def main():
    with euler.TimeWrapper():
        result = sum([n for n in fibonacci(4000000) if n%2==0])
        print result

if __name__ == '__main__':
    main()
