#!/usr/bin/python2

"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
Pentagonal  Pn=n(3n-1)/2  1, 5, 12, 22, 35, ...
Hexagonal   Hn=n(2n-1)    1, 6, 15, 28, 45, ...
It can be verified that T_{285} = P_{165} = H_{143} = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from __future__ import division

import math
import itertools
import euler

def triangular(n):
    return n*(n+1)/2

def pent_index(p):
    return (1/6)*(math.sqrt(24*p+1)+1)
def is_pentagonal(p):
    n = pent_index(p)
    return int(n) == n

def hex_index(h):
    return (1/4)*(math.sqrt(8*h+1)+1)
def is_hexagonal(h):
    n = hex_index(h)
    return int(n) == n

def main():
    with euler.TimeWrapper():
        for n in itertools.count(286):
            t = triangular(n)
            if is_pentagonal(t) and is_hexagonal(t):
                print int(t)
                return

if __name__ == "__main__":
    main()

